version: 2.1
executors:
  go_executor:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ray846/fops

jobs:
  build:
    executor: go_executor
    steps:
    
      - checkout
      - run: go get github.com/ray846/fops
      - run: make build
      - run: go test ./...
      - run: mkdir release
      - run: mv fops ./release/fops
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t 1c3a6b137d25ab5d08c20793eb171c17ae5a5127 -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -delete v0.0.1 ./release
workflows:
  version: 2
  build:
    jobs:
      - build