# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
executors:
  goExecutor:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ray846/fops

jobs:
  build:
    executor: goExecutor
    steps:
    
      - checkout
      - run: go get github.com/ray846/fops
      - run: make build
  test:
    executor: goExecutor
    steps:

      - run: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build