version: 2.1
executors:
  go_executor:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ray846/fops

jobs:
  build:
    executor: go_executor
    steps:
    
      - checkout
      - run: go get github.com/ray846/fops
      - run: make build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: /go/src/github.com/ray846/fops
          # Must be relative path from root
          paths:
            - fops
  test:
    executor: go_executor
    steps:

      - run: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build