version: 2.1
executors:
  go_executor:
    docker:
      - image: circleci/golang:1.9
      - image: cibuilds/github:0.10
    working_directory: /go/src/github.com/ray846/fops

jobs:
  build:
    executor: go_executor
    steps:    
      - checkout
      - run: go get github.com/ray846/fops
      - run: make build
      - run: go test ./...
  publish-github-release:
    executor: go_executor
    steps:
      - checkout
      - run: go get github.com/ray846/fops
      - run: make build
      - run: mkdir release
      - run: mv ./fops ./release/fops
      - run: go get github.com/tcnksm/ghr
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(./release/fops version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./release/

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/