version: 2.1
executors:
  go_executor:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ray846/fops

jobs:
  build:
    executor: go_executor
    steps:
    
      - checkout
      - run: go get github.com/ray846/fops
      - run: make build
      - run: go test ./...
      - run: mkdir release
      - run: mv fops ./release/fops
      - run: go get github.com/tcnksm/ghr
      - run: VERSION=v0.0.1
      - run: GITHUB_TOKEN=eaac9e33035aeb3aa3faf391b157cb99c71eefd4
      - run: ghr -t ${GITHUB_TOKEN} -delete ${VERSION} ./release
workflows:
  version: 2
  build:
    jobs:
      - build